export const Router = {
  events: "/",
  settings: "/settings",
  userInfo: "/userInfo",
  myEvents: "/myEvents",
  categories: "/Categories",
  category: "/Category",
  maps: "/Maps",
  account: "/Account",
  music: "/Music",
  social: "/Social",
  comedy: "/Comedy",
  eventDetail: "/EventDetail",
  login: "/login",
  signup: "/signup",
  create: "/Create",
  createLocation: "/Create/Location",
  createEvent: "/Create/Event",
};
